//Warning: This file is automatically generated by CMake. Do NOT EDIT this file directly !!
#ifndef __HAL_DEFS_H__
#define __HAL_DEFS_H__
#define HAL_RADIO_INCLUDE_TIMESTAMP
#endif //__HAL_DEFS_H__
